/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2019-09-24 07:59:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1569207694791L));
    _jspx_dependants.put("jar:file:/C:/SSAFY2/work_servlet_jsp/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/safefood_webbackend/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.4.1.js\"\r\n");
      out.write("\tintegrity=\"sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=\"\r\n");
      out.write("\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css\">\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("<link href=\"jumbotron.css\" rel=\"stylesheet\">\r\n");
      out.write("<script src=\"../../assets/js/ie-emulation-modes-warning.js\"></script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("fieldset.scheduler-border {\r\n");
      out.write("\twidth: 40%;\r\n");
      out.write("\tborder: 1px groove #ddd !important;\r\n");
      out.write("\tpadding: 0 1.4em 1.4em 1.4em !important;\r\n");
      out.write("\tmargin: 0 0 1.5em 0 !important;\r\n");
      out.write("\t-webkit-box-shadow: 0px 0px 0px 0px #000;\r\n");
      out.write("\tbox-shadow: 0px 0px 0px 0px #000;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("legend.scheduler-border {\r\n");
      out.write("\tfont-size: 1.2em !important;\r\n");
      out.write("\tfont-weight: bold !important;\r\n");
      out.write("\ttext-align: left !important;\r\n");
      out.write("\twidth: auto;\r\n");
      out.write("\tpadding: 0 10px;\r\n");
      out.write("\tborder-bottom: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container {\r\n");
      out.write("\twidth: 750px;\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-control {\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\twidth: 50%;\r\n");
      out.write("}\r\n");
      out.write(".popover{\r\n");
      out.write("\twidth: 300px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\t\r\n");
      out.write("\tvar msg = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${msg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("\tif(msg==\"success\"){\r\n");
      out.write("\t\talert(\"등록 성공입니다.\");\r\n");
      out.write("\t}else if(msg==\"fail\"){\r\n");
      out.write("\t\talert(\"등록 실패입니다.\");\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\t$('#login').popover({\r\n");
      out.write("\t\t\tplacement : 'bottom',\r\n");
      out.write("\t\t\thtml : true,\r\n");
      out.write("\t\t\tcontent : $('#myForm').html()\r\n");
      out.write("\t\t}).on('click', function() {\r\n");
      out.write("\t\t\t$(function() {\r\n");
      out.write("\t\t\t\t$('.popover-content').css('background-color', '#465355');\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t$(function() {\r\n");
      out.write("\t\t\t\t$('.popover-title').css('background-color', '#465355');\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t// had to put it within the on click action so it grabs the correct info on submit\r\n");
      out.write("\t\t\t$('.btn-primary').click(function() {\r\n");
      out.write("\t\t\t\t$.post('/echo/html/', {\r\n");
      out.write("\t\t\t\t\temail : $('#email').val(),\r\n");
      out.write("\t\t\t\t\tname : $('#password').val()\r\n");
      out.write("\t\t\t\t}, function(r) {\r\n");
      out.write("\t\t\t\t\t$('#pops').popover('hide')\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t})\r\n");
      out.write("\t})\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<nav class=\"navbar navbar-inverse\">\r\n");
      out.write("\t\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"navbar-toggle collapsed\"\r\n");
      out.write("\t\t\t\t\tdata-toggle=\"collapse\" data-target=\"#navbar\" aria-expanded=\"false\"\r\n");
      out.write("\t\t\t\t\taria-controls=\"navbar\">\r\n");
      out.write("\t\t\t\t\t<span class=\"sr-only\">Toggle navigation</span> <span\r\n");
      out.write("\t\t\t\t\t\tclass=\"icon-bar\"></span> <span class=\"icon-bar\"></span> <span\r\n");
      out.write("\t\t\t\t\t\tclass=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t<a class=\"navbar-brand\" href=\"#\"></a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<a href=\"./main.html\"> <img src=\"./img/ssafy.png\"></a>\r\n");
      out.write("\t<ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("\t\t<li class=\"active\"><a href=\"#\" style=\"margin-right: 30px\">공지\r\n");
      out.write("\t\t\t\t사항 </a></li>\r\n");
      out.write("\t\t<li><a href=\"./productInfo.html\" style=\"margin-right: 30px\">상품\r\n");
      out.write("\t\t\t\t정보</a></li>\r\n");
      out.write("\t\t<li><a href=\"#\" style=\"margin-right: 30px\">베스트 섭취 정보</a></li>\r\n");
      out.write("\t\t<li><a href=\"#\" style=\"margin-right: 30px\">예상 섭취 정보</a></li>\r\n");
      out.write("\t\t<li><a href=\"#\" class=\"glyphicon glyphicon-search\"\r\n");
      out.write("\t\t\tstyle=\"margin-right: 100px\"></a></li>\r\n");
      out.write("\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Main jumbotron for a primary marketing message or call to action -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"jumbotron\"\r\n");
      out.write("\t\tstyle=\"background-color: #A9A9A9; margin-bottom: 0px\">\r\n");
      out.write("\t\t<div class=\"container\" style=\"text-align: center\">\r\n");
      out.write("\t\t\t<h1 style=\"color: white\">WHAT WE PROVIDE</h1>\r\n");
      out.write("\t\t\t<hr>\r\n");
      out.write("\t\t\t<p style=\"color: white\">건강한 삶을 위한 먹거리 프로젝트</p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<br />\r\n");
      out.write("\t<div class=\"main col-12\" style=\"margin-left: 300px\">\r\n");
      out.write("\t\t<!-- page-title start -->\r\n");
      out.write("\t\t<!-- ================ -->\r\n");
      out.write("\t\t<div class=\"isotope-container row grid-space-10\"\r\n");
      out.write("\t\t\tstyle=\"height: 476.74px; display: block; position: relative;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"col-lg-4 col-md-6 isotope-item app-development\"\r\n");
      out.write("\t\t\t\tstyle=\"left: 0px; top: 0px; position: absolute;\">\r\n");
      out.write("\t\t\t\t<div class=\"image-box hc-shadow-2 text-center mb-20\">\r\n");
      out.write("\t\t\t\t\t<div class=\"overlay-container\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"./pdetail.html\"><img width=\"200\" class=\"center\" alt=\"아카페라아메리카노\"\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"img/아카페라아메리카노.jpg\"></a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"col-lg-4 col-md-6 isotope-item app-development\"\r\n");
      out.write("\t\t\t\tstyle=\"left: 373px; top: 0px; position: absolute;\">\r\n");
      out.write("\t\t\t\t<div class=\"image-box hc-shadow-2 text-center mb-20\">\r\n");
      out.write("\t\t\t\t\t<div class=\"overlay-container\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"><img width=\"200\" class=\"center\" alt=\"누크바\"\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"img/N45누크바.jpg\"></a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"col-lg-4 col-md-6 isotope-item app-development\"\r\n");
      out.write("\t\t\t\tstyle=\"left: 747px; top: 0px; position: absolute;\">\r\n");
      out.write("\t\t\t\t<div class=\"image-box hc-shadow-2 text-center mb-20\">\r\n");
      out.write("\t\t\t\t\t<div class=\"overlay-container\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"><img width=\"200\" class=\"center\" alt=\"비비빅\"\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"img/비비빅.jpg\"></a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"col-lg-4 col-md-6 isotope-item app-development\"\r\n");
      out.write("\t\t\t\tstyle=\"left: 0px; top: 238px; position: absolute;\">\r\n");
      out.write("\t\t\t\t<div class=\"image-box hc-shadow-2 text-center mb-20\">\r\n");
      out.write("\t\t\t\t\t<div class=\"overlay-container\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"><img width=\"200\" class=\"center\" alt=\"서울우유바나나\"\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"img/서울우유바나나.jpg\"></a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"col-lg-4 col-md-6 isotope-item app-development\"\r\n");
      out.write("\t\t\t\tstyle=\"left: 373px; top: 238px; position: absolute;\">\r\n");
      out.write("\t\t\t\t<div class=\"image-box hc-shadow-2 text-center mb-20\">\r\n");
      out.write("\t\t\t\t\t<div class=\"overlay-container\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"><img width=\"200\" class=\"center\" alt=\"메로나\"\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"img/메로나.jpg\"></a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"col-lg-4 col-md-6 isotope-item app-development\"\r\n");
      out.write("\t\t\t\tstyle=\"left: 747px; top: 238px; position: absolute;\">\r\n");
      out.write("\t\t\t\t<div class=\"image-box hc-shadow-2 text-center mb-20\">\r\n");
      out.write("\t\t\t\t\t<div class=\"overlay-container\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"><img width=\"200\" class=\"center\" alt=\"진라면컵매운맛\"\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"img/진라면컵매운맛.jpg\"></a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- main end -->\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"myForm\" class=\"hide\">\r\n");
      out.write("\t<!-- 로그인 Form -->\r\n");
      out.write("\t\t<form action=\"main.do?action=Login\" id=\"popForm\" method=\"post\">\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<label for=\"email\" style=\"color:white;\" >ID</label> <br/><input type=\"text\" name=\"pid\"\r\n");
      out.write("\t\t\t\t\tid=\"email\" class=\"form-control input-md\"\r\n");
      out.write("\t\t\t\t\tstyle=\"background-color: #677475;\"> \r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div>\t\t\r\n");
      out.write("\t\t\t\t<label for=\"password\" style=\"color:white;\" >비밀번호</label> <br/>\r\n");
      out.write("\t\t\t\t<input type=\"password\" name=\"ppw\" id=\"name\"\r\n");
      out.write("\t\t\t\t\tclass=\"form-control input-md\" style=\"background-color: #677475;\">\r\n");
      out.write("\t\t\t\t<div style=\"margin-top:20px\">\r\n");
      out.write("\t\t\t\t<button type=\"submit\" >로 그 인</button>\r\n");
      out.write("\t\t\t\t<button type=\"button\" >비밀번호 찾기</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"result\"></div>\r\n");
      out.write("\t<div class=\"modal fade\" id=\"myModal\" role=\"dialog\">\r\n");
      out.write("\t\t<div class=\"modal-dialog\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t<!-- 회원등록  form -->\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\">×</button>\r\n");
      out.write("\t\t\t\t\t\t<h3 class=\"modal-title\">Sign Up</h3>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<form action=\"main.do?action=SignUp\"name=\"registerform\" method=\"post\" action=\"./register\">\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"cntainer\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"well\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label for=\"email\">ID*:</label> <br /> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"form-control\" id=\"email\" name=\"pid\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label for=\"pwd\">Password*:</label><br /> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttype=\"password\" class=\"form-control\" id=\"pwd\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"Enter password\" name=\"ppw1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label for=\"userPwCheck\">비밀번호 확인*</label><br /> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttype=\"password\" id=\"userPwCheck\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tmaxlength=\"20\" autocomplete=\"off\" name=\"ppw2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label for=\"username\">이름*</label><br /> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tid=\"userId\" class=\"form-control\" maxlength=\"20\" value=\"\" name=\"pname\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label for=\"useradress\">주소*</label><br /> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tid=\"userId\" class=\"form-control\" maxlength=\"20\" value=\"\" name=\"paddr\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label for=\"email01\">이메일*</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"email01\" class=\"form-inline\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tname=\"pemail1\" size=\"20\" maxlength=\"20\" value=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tautocomplete=\"off\"><span>@</span> <input id=\"email02\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tname=\"pemail2\" class=\"form-inline\" list=\"domains\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"도메인입력/선택\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<datalist id=\"domains\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"naver.com\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"daum.net\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"gmail.com\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"yahoo.co.kr\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</datalist>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"fieldlabel\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label for=\"mPhone1\">전화번호</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"formfield\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<select id=\"mPhone1\" name=\"ptel1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"010\" selected>010</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"011\">011</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"016\">017</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"018\">018</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"019\">019</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</select>- <input id=\"mPhone2\" name=\"ptel2\" type=\"number\" value=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tsize=\"4\" maxlength=\"4\" autocomplete=\"off\">- <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tid=\"mPhone3\" name=\"ptel3\" type=\"number\" value=\"\" size=\"4\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tmaxlength=\"4\" autocomplete=\"off\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<fieldset class=\"scheduler-border\" id=\"option\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<legend class=\"scheduler-border\">알레르기*</legend>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"formfield\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" name=\"hobby\" value=\"대두\" alt=\"취미\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t대두 <input type=\"checkbox\" name=\"hobby\" value=\"땅콩\" alt=\"취미\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t땅콩 <input type=\"checkbox\" name=\"hobby\" value=\"우유\" alt=\"취미\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t우유 <input type=\"checkbox\" name=\"hobby\" value=\"우유\" alt=\"취미\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t게 <br> <input type=\"checkbox\" name=\"hobby\" value=\"새우\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\talt=\"취미\"> 새우 <input type=\"checkbox\" name=\"hobby\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tvalue=\"참치\" alt=\"취미\"> 참치 <input type=\"checkbox\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tname=\"hobby\" value=\"연어\" alt=\"취미\"> 연어 <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\ttype=\"checkbox\" name=\"hobby\" value=\"쑥\" alt=\"취미\"> 쑥 <br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" name=\"hobby\" value=\"소고기\" alt=\"취미\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t소고기 <input type=\"checkbox\" name=\"hobby\" value=\"닭고기\" alt=\"취미\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t닭고기 <input type=\"checkbox\" name=\"hobby\" value=\"돼지고기\" alt=\"취미\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t돼지고기 <br> <input type=\"checkbox\" name=\"hobby\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tvalue=\"복숭아\" alt=\"취미\"> 복숭아 <input type=\"checkbox\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tname=\"hobby\" value=\"민들레\" alt=\"취미\"> 민들레 <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\ttype=\"checkbox\" name=\"hobby\" value=\"계란흰자\" alt=\"취미\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t계란흰자\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" class=\"btn btn-primary btn-sm\" value=\"등록\">\r\n");
      out.write("\t\t\t\t\t\t<button algin=\"right\" type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"footer\" style=\"background-color: #F8F8FF\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"footer-inner\">\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-10\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"footer-content\">\r\n");
      out.write("\t\t\t\t\t\t\t<h2 class=\"title\">Find Us</h2>\r\n");
      out.write("\t\t\t\t\t\t\t<hr>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"separator-2\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"list-icons\" style=\"list-style: none;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li style=\"opacity: 0.6\"><img src=\"./img/위치.png\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\twidth=\"20px\"> (SSAFY) 서울시 강남구 테헤란로 멀티스퀘어</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li style=\"opacity: 0.6\"><img src=\"./img/전화.png\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\twidth=\"20px\"> 1544-9001</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li style=\"opacity: 0.6\"><a href=\"#\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"./img/이메일.png\" width=\"20px\"> admin@ssafy.com</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"subfooter\" style=\"background-color: #F5F5F5\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"subfooter-inner\">\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\t\t<p class=\"text-center\" style=\"opacity: 0.6\">Copyright by\r\n");
      out.write("\t\t\t\t\t\t\tSSAFY. All rights reserved.</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /main.jsp(104,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${islogin ne 'isLogin'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t<div id=\"navbar\" class=\"navbar-collapse collapse\">\r\n");
          out.write("\t\t\t\t\t<ul class=\"nav navbar-nav navbar-right\">\r\n");
          out.write("\t\t\t\t\t\t<li><a data-toggle=\"modal\" href=\"#myModal\"><img width=\"20px\" src=\"./img/사람.png\">Sign\r\n");
          out.write("\t\t\t\t\t\t\t\tUp</a></li>\r\n");
          out.write("\t\t\t\t\t\t<li id=login><a href=\"#\"><img width=\"20px\" src=\"./img/사람.png\">Login</a></li>\r\n");
          out.write("\t\t\t\t\t</ul>\r\n");
          out.write("\t\t\t\t</div>\r\n");
          out.write("\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /main.jsp(113,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${islogin eq 'isLogin'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t<div id=\"navbar\" class=\"navbar-collapse collapse\">\r\n");
          out.write("\t\t\t\t\t<ul class=\"nav navbar-nav navbar-right\">\r\n");
          out.write("\t\t\t\t\t\t<li><a href=\"mypage.jsp\"><img width=\"20px\" src=\"./img/사람.png\">회원정보수정</a></li>\r\n");
          out.write("\t\t\t\t\t\t<li id=logout><a href=\"main.do?action=Logout\"><img width=\"20px\" src=\"./img/사람.png\">Logout</a></li>\r\n");
          out.write("\t\t\t\t\t</ul>\r\n");
          out.write("\t\t\t\t</div>\r\n");
          out.write("\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }
}
